# Generated by Django 4.2.1 on 2023-06-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netflixapp.contactinfo')),
                ('phone', models.CharField(max_length=12)),
            ],
            bases=('netflixapp.contactinfo',),
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netflixapp.contactinfo')),
                ('position', models.CharField(max_length=12)),
            ],
            bases=('netflixapp.contactinfo',),
        ),
    ]
