# Generated by Django 4.2.1 on 2023-06-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0004_person_myperson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myperson',
        ),
        migrations.DeleteModel(
            name='person',
        ),
    ]
